name: mirrorprism
favicon: null
layout_spectrum: 0.25341
typography_spectrum: 0.21485621551983058
title: 'Photography, Cinematography, Motion Graphics'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1617'
    - '#172a6d'
    - '#7a8db4'
    - '#63182f'
    - '#705b5f'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
