name: mirrorprism
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09732
title: 'Photography, Cinematography, Motion Graphics'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1617'
    - '#172a6d'
    - '#7a8db4'
    - '#63182f'
    - '#705b5f'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
